name = "cowboy-do-memory-mock"
main = "src/index.ts"
compatibility_date = "2026-07-11"
workers_dev = true

[durable_objects]
bindings = [{ name = "HUB", class_name = "CowboyHubMock" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CowboyHubMock"]
