#!/usr/bin/env python3
"""Research Codex hook placement using the existing isolated native fixture.

Only the exact hashes of hooks generated by this probe are trusted in its new
private home. Never use this fixture's trust setup for live sessions.
"""

import argparse
import hashlib
import json
import os
from pathlib import Path
import shlex
import socket
import subprocess
import tempfile
from unittest.mock import patch

import execution_environment_codex_turn_probe as native
from execution_environment_probe import require


def probe(binary):
    observed = {}
    original_write = Path.write_text
    original_spawn = subprocess.Popen
    original_stop = native.stop
    original_app = native.app
    logs = []

    def app(binary, environment, runtime):
        client = original_app(binary, environment, runtime)
        response = client.request("hooks/list", {"cwds": [str(runtime)]})
        hooks = response["data"][0]["hooks"]
        require(len(hooks) == 4, "unexpected fixture hook inventory")
        if any(hook["trustStatus"] != "trusted" for hook in hooks):
            client.close()
            config = Path(environment["CODEX_HOME"]) / "config.toml"
            contents = config.read_text()
            for hook in hooks:
                require(hook["sourcePath"] == str(config.parent / "hooks.json"), "foreign hook source")
                contents += f'\n[hooks.state.{json.dumps(hook["key"])}]\ntrusted_hash = {json.dumps(hook["currentHash"])}\n'
            original_write(config, contents)
            client = original_app(binary, environment, runtime)
            checked = client.request("hooks/list", {"cwds": [str(runtime)]})
            require(all(hook["trustStatus"] == "trusted" for hook in checked["data"][0]["hooks"]), "fixture hook trust did not apply")
        return client

    def write(path, data, *args, **kwargs):
        if path.name == "config.toml" and 'model_provider = "cowboy_fixture"' in data:
            root = path.parent.parent.parent
            log = root / "hook-observations.jsonl"
            script = root / "hook-observer.py"
            original_write(script,
                           "import json,os,sys\n"
                           "event=json.load(sys.stdin)\n"
                           "parent=os.getppid();owners=[]\n"
                           "for _ in range(20):\n"
                           " try:\n"
                           "  argv=open(f'/proc/{parent}/cmdline','rb').read().split(b'\\x00')\n"
                           "  owners += [word.decode() for word in argv if word in (b'app-server',b'exec-server')]\n"
                           "  if owners: break\n"
                           "  parent=int(open(f'/proc/{parent}/stat').read().rsplit(')',1)[1].split()[1])\n"
                           "  if parent <= 1: break\n"
                           " except (FileNotFoundError,ProcessLookupError): break\n"
                           f"with open({str(log)!r},'a') as f:\n"
                           " f.write(json.dumps({'event':event.get('hook_event_name'),"
                           "'cwd':os.getcwd(),'origin':os.environ.get('COWBOY_PROBE_ORIGIN'),'owners':owners})+'\\n')\n")
            command = f"{shlex.quote(os.sys.executable)} {shlex.quote(str(script))}"
            hooks = {event: [{"hooks": [{"type": "command", "command": command}]}]
                     for event in ("SessionStart", "PreToolUse", "PostToolUse", "Stop")}
            original_write(path.parent / "hooks.json", json.dumps({"hooks": hooks}))
            observed["log"] = log
        return original_write(path, data, *args, **kwargs)

    def spawn(args, *positional, **kwargs):
        argv = list(args)
        if "app-server" in argv or "exec-server" in argv:
            environment = dict(kwargs["env"])
            environment["COWBOY_PROBE_ORIGIN"] = "target" if "exec-server" in argv else "runtime"
            kwargs["env"] = environment
        if "app-server" in argv:
            argv[1:1] = ["-c", "features.hooks=true"]
            log = tempfile.TemporaryFile()
            logs.append(log)
            kwargs["stderr"] = log
        return original_spawn(argv, *positional, **kwargs)

    def stop(process):
        original_stop(process)
        log = observed.get("log")
        observed["events"] = [json.loads(line) for line in log.read_text().splitlines()] if log and log.exists() else []

    with patch.object(Path, "write_text", write), patch.object(subprocess, "Popen", spawn), patch.object(native, "stop", stop), patch.object(native, "app", app):
        checks = native.probe(str(binary), "0.159.3")
    events = observed.get("events", [])
    for log in logs:
        log.close()
    require(any(event["event"] == "PreToolUse" for event in events), "hook positive control did not run")
    # Discard temporary directory names, retaining which workspace was used.
    for event in events:
        event["cwd"] = Path(event["cwd"]).name
    return {"native_checks": checks, "hook_observations": events,
            "remote_hook_count": len(events)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--native-cli", type=Path, required=True)
    parser.add_argument("--sha256", required=True)
    parser.add_argument("--receipt", type=Path, required=True)
    args = parser.parse_args()
    require(args.native_cli.is_absolute(), "absolute native CLI required")
    require(args.receipt.is_absolute() and not args.receipt.exists(), "new absolute receipt required")
    require(os.readlink("/proc/self/ns/net") != os.readlink("/proc/1/ns/net"), "new network namespace required")
    require([name for _, name in socket.if_nameindex()] == ["lo"], "only loopback may exist")
    digest = hashlib.sha256(args.native_cli.read_bytes()).hexdigest()
    require(digest == args.sha256, "native CLI digest differs")
    result = {"schema": "cowboy.remote-native-hooks-research/v1", "native_sha256": digest,
              "real_model_requests": 0, "production_credentials": False,
              "scope": "user command hooks; isolated native remote environment; not project discovery"}
    result.update(probe(args.native_cli))
    with args.receipt.open("x") as output:
        json.dump(result, output, indent=2)
        output.write("\n")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
