// Cowboy-local Codex activity copy. These are intentionally playful UI phrases,
// NOT ACP reasoning events and never presented as a report of actual operations.
export const CODEX_ACTIVITY_PHRASES: readonly string[] = [
  "Aligning latent manifolds",
  "Balancing token pressure",
  "Braiding execution paths",
  "Calibrating context flux",
  "Chasing invariant ghosts",
  "Coalescing semantic shards",
  "Compiling a better hunch",
  "Compressing the possibility space",
  "Convolving intent vectors",
  "Decoding architectural sediment",
  "Defragmenting the thought heap",
  "Diffing alternate timelines",
  "Distilling executable meaning",
  "Entangling useful abstractions",
  "Enumerating edge universes",
  "Folding branches into focus",
  "Garbage-collecting weak hypotheses",
  "Grep-walking the idea graph",
  "Hashing the unknown unknowns",
  "Hydrating dormant context",
  "Indexing the causal lattice",
  "JIT-compiling intuition",
  "Linking conceptual objects",
  "Lowering intent to operations",
  "Memoizing promising detours",
  "Normalizing the weird machine",
  "Optimizing for fewer surprises",
  "Parsing the problem topology",
  "Patching holes in the model",
  "Pipelining possible answers",
  "Probing the state space",
  "Rebasing onto reality",
  "Reconciling competing invariants",
  "Reducing semantic entropy",
  "Resolving dependency weather",
  "Reticulating control flow",
  "Sampling adjacent solutions",
  "Scheduling tiny revelations",
  "Sharding the reasoning graph",
  "Speculating under type safety",
  "Splicing causal threads",
  "Stacking useful constraints",
  "Synthesizing a cleaner path",
  "Tracing invisible contracts",
  "Transpiling ambiguity",
  "Type-checking the intuition",
  "Unrolling the consequence loop",
  "Vectorizing the hunch engine",
  "Verifying the vibes",
  "Warming the inference cache",
  "Weaving context into code",
  "Wrangling nondeterministic ducks",
  "Zeroing in on the sharp edge",
  "Auditing the assumption stack",
  "Backpropagating from the outcome",
  "Bootstrapping a mental sandbox",
  "Canonicalizing loose ends",
  "Checkpointing the useful bits",
  "Clustering suspicious details",
  "Committing provisional wisdom",
  "Debouncing premature conclusions",
  "Desugaring the problem statement",
  "Eliding unnecessary dimensions",
  "Evaluating counterfactual branches",
  "Fusing evidence streams",
  "Hoisting the important constraint",
  "Inverting the failure surface",
  "Lexing the human intent",
  "Mapping the blast radius",
  "Mining the context window",
  "Negotiating with the edge cases",
  "Peeking behind the abstraction",
  "Precomputing future regret",
  "Pruning implausible timelines",
  "Reconstructing the hidden contract",
  "Reifying the fuzzy requirement",
  "Routing around accidental complexity",
  "Simulating the unhappy path",
  "Stabilizing the semantic orbit",
  "Threading the concurrency maze",
  "Triangulating from partial evidence",
  "Untangling async spaghetti",
  "Validating the escape velocity",
  "Walking the dependency graph",
  "Whispering to the type system",
  "Amortizing the cognitive load",
  "Bending the branch predictor",
  "Calculating the least-wrong move",
  "Coaxing order from the event loop",
  "Deduplicating parallel thoughts",
  "Factoring the conceptual polynomial",
  "Finding the load-bearing assumption",
  "Flattening nested uncertainty",
  "Interleaving insight packets",
  "Measuring twice in hyperspace",
  "Performing semantic archaeology",
  "Repacking the context suitcase",
  "Solving for maintainability",
  "Sorting the epistemic queue",
  "Spinning up a pocket universe",
  "Testing the counterexample generator",
  "Tuning the abstraction boundary",
  "Unifying the divergent timelines",
  "Vacuuming stale mental state",
  "Yielding to the stronger invariant",
];
