// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/detent-sheet.tsx
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// DetentSheet — a momentum bottom sheet with two heights (detents), for mobile.
//
// Self-contained overlay: it renders a fixed scrim + sheet INSIDE the caller's
// own tree and touches nothing else. Deliberately NOT a MUI Modal — a Modal
// mounts into document.body, locks body scroll, and sets aria-hidden on #root
// (which, in the atlantis portal, holds a hosted app's cross-origin iframe). On
// iOS those document mutations perturb the visual viewport, which the portal
// mirrors into the iframe height — so opening the sheet flashed the app behind
// it. This overlay has ZERO document-level side effects: no portal-to-body, no
// scroll lock, no attributes on #root or the iframe. That property is harmless
// for a standalone app and required for the portal, so every app shares it.
//
// Dependency-free on purpose. The SDK is *vendored* (copied into each app), so
// it must not drag animation libraries into every app's deps. The drag follows
// the finger via one rAF-coalesced style write per frame (no React render, the
// same trick bottom-sheet.tsx uses); the release settle (snap / dismiss / the
// open slide-in) rides a CSS transition. translateY only — a compositor
// property — with will-change + contain bounding the work to the sheet.
//
// Mobile only — the caller renders a centered dialog on desktop (see
// bottom-sheet.tsx), where a sheet and its drag handle read wrong on a wide
// pointer-driven screen.

import { Box } from "@mui/material";
import {
  type PointerEvent as ReactPointerEvent,
  type ReactNode,
  useCallback,
  useEffect,
  useRef,
  useState,
} from "react";

// Detents as the fraction of the viewport the sheet reveals: a medium "peek"
// and a near-full expansion (a scrim strip always stays). The sheet's height is
// the tall detent; the short one is reached by sliding it partway down.
const DETENTS = [0.5, 0.88] as const;
const SHEET_FRACTION = DETENTS[DETENTS.length - 1] ?? 0.88;
const OPEN_AT = 0; // detent index the sheet opens at (medium)

// Release velocity (px/ms) projects this far forward to choose the detent; a
// downward flick faster than this dismisses instead of snapping.
const PROJECTION_MS = 110;
const FLICK_DISMISS = 0.55;
// Settle duration + easing for snap / dismiss / open. An ease-out curve that
// reads as a snappy, lightly-damped spring without a physics library.
const SETTLE_MS = 320;
const SETTLE_EASE = "cubic-bezier(0.22, 1, 0.36, 1)";
// Scrim darkens as the sheet rises (0 closed → this at full).
const SCRIM_MAX = 0.45;
// Above the app chrome (banners are z=10) and the iframe. Self-contained, so a
// plain high z-index is enough; no portal/Modal stacking to coordinate with.
const Z = 1300;
const SAFE_BOTTOM = "calc(16px + env(safe-area-inset-bottom, 0px))";

const clamp = (v: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, v));

export interface DetentSheetProps {
  readonly open: boolean;
  readonly onClose: () => void;
  // `| undefined` (not just `?`) so a caller compiling with
  // exactOptionalPropertyTypes can pass an explicit undefined (see ui.md §8).
  readonly ariaLabel?: string | undefined;
  /** The top bar — the drag affordance (a grab handle is prepended). Buttons in
   *  here should `stopPropagation` on pointerdown so a tap acts, not drags. */
  readonly header: ReactNode;
  /** Scrollable body below the header. */
  readonly children: ReactNode;
  /** Optional row pinned to the bottom (e.g. Save / Cancel), safe-area padded. */
  readonly footer?: ReactNode;
}

export function DetentSheet({ open, onClose, ariaLabel, header, children, footer }: DetentSheetProps): ReactNode {
  const sheetRef = useRef<HTMLDivElement | null>(null);
  const scrimRef = useRef<HTMLDivElement | null>(null);
  const yRef = useRef(0); // current translateY (px)
  const geomRef = useRef<{ detents: number[]; closedPx: number }>({ detents: [0, 0], closedPx: 0 });
  const dragRef = useRef<{ startPointerY: number; startY: number; samples: { t: number; y: number }[] } | null>(null);
  const rafRef = useRef(0);

  // The detent the sheet is RESTING at (fraction of viewport). The scroll body
  // is capped to this detent's visible area so an overflowing list shows a
  // scrollbar instead of running off-screen below the fold. Updated only on
  // settle; during a drag the cap is lifted so content fills as it grows.
  const [restFrac, setRestFrac] = useState<number>(DETENTS[OPEN_AT] ?? 0.5);
  const [dragging, setDragging] = useState(false);
  // Measured top-bar height, subtracted from the detent to cap the scroll area.
  const [barH, setBarH] = useState(88);
  const barRef = useCallback((node: HTMLDivElement | null): void => {
    if (node) setBarH(node.offsetHeight);
  }, []);

  // Write translateY + scrim opacity straight to the DOM (no React render). The
  // settle rides a CSS transition; an active drag turns it off so the sheet
  // tracks the finger 1:1.
  const paint = useCallback((y: number, animate: boolean): void => {
    yRef.current = y;
    const { closedPx } = geomRef.current;
    const sheet = sheetRef.current;
    const scrim = scrimRef.current;
    if (sheet) {
      sheet.style.transition = animate ? `transform ${String(SETTLE_MS)}ms ${SETTLE_EASE}` : "none";
      sheet.style.transform = `translateY(${String(y)}px)`;
    }
    if (scrim) {
      scrim.style.transition = animate ? `opacity ${String(SETTLE_MS)}ms ${SETTLE_EASE}` : "none";
      scrim.style.opacity = String(closedPx > 0 ? clamp((closedPx - y) / closedPx, 0, 1) * SCRIM_MAX : 0);
    }
  }, []);

  // (Re)compute geometry against the viewport on open, then animate in.
  useEffect(() => {
    if (!open) return undefined;
    const h = window.innerHeight;
    const sheetPx = SHEET_FRACTION * h;
    geomRef.current = { detents: DETENTS.map((f) => sheetPx - f * h), closedPx: sheetPx };
    setRestFrac(DETENTS[OPEN_AT] ?? 0.5);
    setDragging(false);
    const openY = geomRef.current.detents[OPEN_AT] ?? 0;
    paint(geomRef.current.closedPx, false); // seed closed (no transition)…
    const id = window.requestAnimationFrame(() => paint(openY, true)); // …then slide up
    return () => window.cancelAnimationFrame(id);
  }, [open, paint]);

  const dismiss = useCallback((): void => {
    paint(geomRef.current.closedPx, true);
    window.setTimeout(onClose, SETTLE_MS);
  }, [paint, onClose]);

  const onPointerDown = useCallback((e: ReactPointerEvent<HTMLDivElement>): void => {
    e.preventDefault();
    e.currentTarget.setPointerCapture(e.pointerId);
    dragRef.current = { startPointerY: e.clientY, startY: yRef.current, samples: [{ t: e.timeStamp, y: e.clientY }] };
    setDragging(true);
  }, []);

  const onPointerMove = useCallback(
    (e: ReactPointerEvent<HTMLDivElement>): void => {
      const d = dragRef.current;
      if (!d) return;
      const { closedPx } = geomRef.current;
      let y = d.startY + (e.clientY - d.startPointerY);
      if (y < 0) y *= 0.12; // rubberband past the top
      y = Math.min(y, closedPx);
      d.samples.push({ t: e.timeStamp, y: e.clientY });
      if (d.samples.length > 5) d.samples.shift();
      if (rafRef.current === 0) {
        rafRef.current = window.requestAnimationFrame(() => {
          rafRef.current = 0;
          paint(y, false);
        });
      }
    },
    [paint],
  );

  const onPointerUp = useCallback((): void => {
    const d = dragRef.current;
    dragRef.current = null;
    setDragging(false);
    if (rafRef.current !== 0) {
      window.cancelAnimationFrame(rafRef.current);
      rafRef.current = 0;
    }
    if (!d) return;
    const { detents, closedPx } = geomRef.current;
    const last = d.samples[d.samples.length - 1];
    const prev = d.samples[d.samples.length - 2] ?? last;
    if (!last || !prev) return;
    const dt = last.t - prev.t;
    const vy = dt > 0 ? (last.y - prev.y) / dt : 0; // px/ms, + = downward
    const projected = yRef.current + vy * PROJECTION_MS;
    const low = detents[0] ?? 0;
    if (vy > FLICK_DISMISS || projected > low + (closedPx - low) * 0.5) {
      dismiss();
      return;
    }
    let best = 0;
    detents.forEach((dd, i) => {
      if (Math.abs(dd - projected) < Math.abs((detents[best] ?? 0) - projected)) best = i;
    });
    setRestFrac(DETENTS[best] ?? DETENTS[OPEN_AT] ?? 0.5);
    paint(detents[best] ?? 0, true);
  }, [dismiss, paint]);

  // Escape closes — keyboard parity with a dialog, without being a Modal.
  useEffect(() => {
    if (!open) return undefined;
    const onKey = (e: KeyboardEvent): void => {
      if (e.key === "Escape") dismiss();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open, dismiss]);

  // Unmounted when closed; the dismiss runs the settle (open still true) and
  // only then calls onClose, so the slide-out is seen.
  if (!open) return null;

  return (
    <>
      {/* Scrim: dims the app, taps dismiss. Painted imperatively (opacity tracks
          the sheet height). Self-contained — it does NOT touch #root/body. */}
      <Box
        ref={scrimRef}
        aria-hidden
        onClick={dismiss}
        sx={{ position: "fixed", inset: 0, bgcolor: "common.black", zIndex: Z, opacity: 0, touchAction: "none" }}
      />
      <Box
        ref={sheetRef}
        role="dialog"
        aria-modal="true"
        aria-label={ariaLabel}
        sx={{
          position: "fixed",
          left: 0,
          right: 0,
          bottom: 0,
          height: `${String(SHEET_FRACTION * 100)}vh`,
          zIndex: Z + 1,
          willChange: "transform",
          contain: "layout paint",
          display: "flex",
          flexDirection: "column",
          bgcolor: "background.paper",
          borderTopLeftRadius: 16,
          borderTopRightRadius: 16,
          boxShadow: 8,
          outline: "none",
          // Pre-paint: offscreen until the open effect's first frame slides it up.
          transform: "translateY(100vh)",
        }}
      >
        {/* Drag affordance: the whole top bar (grab strip + header) moves the
            sheet. touchAction:none so the browser doesn't claim the gesture for
            scroll/pull-to-refresh; header buttons stopPropagation so a tap acts. */}
        <Box
          ref={barRef}
          onPointerDown={onPointerDown}
          onPointerMove={onPointerMove}
          onPointerUp={onPointerUp}
          sx={{ flexShrink: 0, touchAction: "none", cursor: "grab" }}
        >
          <Box sx={{ display: "flex", justifyContent: "center", alignItems: "center", minHeight: 34, pt: 1 }}>
            <Box sx={{ width: 56, height: 6, borderRadius: 3, bgcolor: "text.disabled" }} />
          </Box>
          {header}
        </Box>
        {/* Body scrolls independently of the drag; capped to the resting detent's
            visible area (lifted while dragging) so a long list scrolls in view. */}
        <Box
          sx={{
            flex: 1,
            minHeight: 0,
            overflowY: "auto",
            maxHeight: dragging ? "none" : `calc(${String(restFrac * 100)}vh - ${String(barH)}px)`,
            px: 2,
            pb: footer == null ? SAFE_BOTTOM : 1,
          }}
        >
          {children}
        </Box>
        {footer == null ? null : (
          <Box
            sx={{ flexShrink: 0, display: "flex", justifyContent: "flex-end", gap: 1, px: 2, pt: 1, pb: SAFE_BOTTOM }}
          >
            {footer}
          </Box>
        )}
      </Box>
    </>
  );
}
