// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/index.ts
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// Public surface of the atlantis app-shell SDK. Apps import from here:
//
//   import { PortalProvider, usePortal, createAtlantisTheme } from "./_shell";
//
// The portal imports the same protocol types directly from the canonical
// source under columbus/interface/app-shell/.

export {
  PortalLauncherButton,
  type PortalLauncherButtonProps,
} from "./app-grid-button";
export { BottomSheet, type BottomSheetProps } from "./bottom-sheet";
export {
  NavShell,
  type NavShellApi,
  type NavShellProps,
} from "./nav-shell";
export {
  type NavigateOptions,
  type PortalApi,
  PortalProvider,
  type PortalProviderProps,
  usePortal,
  usePortalVisibility,
} from "./provider";
export {
  type AppMeta,
  type BusEvent,
  CHANNEL,
  PROTOCOL_VERSION,
  type ThemeChoice,
  type ThemeMode,
  type Visibility,
} from "./protocol";
export {
  SettingsSheet,
  type SettingsSheetProps,
  ThemeModeControl,
} from "./settings-sheet";
export {
  type ThemeModeState,
  useThemeMode,
} from "./theme-mode";
export {
  type AtlantisThemeOptions,
  createAtlantisTheme,
} from "./theme";
