// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/viewport.ts
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// Keep a bottom-pinned composer / action bar visible above the iOS software
// keyboard, for an app running STANDALONE (i.e. as its own top-level document,
// not inside the atlantis portal iframe — see the note on hosting below).
//
// Why this is needed: on iOS Safari the *layout* viewport doesn't shrink when
// the keyboard opens (only the *visual* viewport does), so a full-height,
// non-scrolling column leaves its bottom bar behind the keyboard. Worse, iOS
// nondeterministically chooses between two reactions when an input is focused:
//   (a) shrink the visual viewport  — good, we can track it; or
//   (b) scroll the page to reveal the input — bad: a pinned bar ends up behind
//       the keyboard and the page can get stuck-scrolled.
// That (a)-vs-(b) coin flip is why naive fixes work only intermittently.
//
// This primitive removes the coin flip:
//   1. Locks the page (html/body) so iOS *cannot* scroll it → forces path (a).
//   2. Sizes #root to window.visualViewport.height (the area above the keyboard)
//      via the `--app-height` custom property.
//   3. rAF-coalesces writes and re-reads once after the keyboard animation
//      settles — iOS reports the post-keyboard height a beat late (WebKit
//      #265578), so a single synchronous read can catch a stale value.
// Height ONLY: do NOT follow visualViewport.offsetTop (e.g. via a transform).
// In Safari that over-lifts the app by a large margin (offsetTop double-counts
// once the page is locked).
//
// HOSTED (inside the atlantis portal's cross-origin iframe) this is effectively
// a no-op: an iframe's own `visualViewport` does not receive the top-level
// keyboard's resize/scroll events. The keyboard is a page-level concern only
// the top-level context can observe, so the PORTAL owns that case (by sizing
// the active <iframe> to its own visual viewport) — the same division of
// responsibility as theme. An app therefore just "fills the box it's given":
// standalone this primitive sizes the box; hosted the portal does.
//
// Usage — call once, as early as possible (top of the entrypoint, before the
// first render), so the body lock + #root height apply before paint:
//
//   import { installAppViewport } from "./_shell";
//   installAppViewport();
//
// Returns a teardown fn; rarely needed since the app lives for the whole
// document lifetime, but handy in tests / HMR.

export interface AppViewportOptions {
  /** id of the root element to size. Default "root". */
  rootId?: string;
}

export function installAppViewport(options: AppViewportOptions = {}): () => void {
  // SSR / non-DOM guard: do nothing without a document.
  if (typeof document === "undefined") {
    return () => {};
  }
  const rootId = options.rootId ?? "root";

  // Inject the lock + height rules once, from JS, so a consuming app needs no
  // special index.html — the SDK owns the whole behaviour.
  const STYLE_ID = "atlantis-app-viewport";
  if (!document.getElementById(STYLE_ID)) {
    const style = document.createElement("style");
    style.id = STYLE_ID;
    style.textContent =
      "html{overflow:hidden}" +
      "body{position:fixed;top:0;left:0;right:0;bottom:0;overflow:hidden;margin:0}" +
      // `100dvh` fallback covers the window before the first measurement / where
      // visualViewport is unsupported; the var wins once we set it.
      `#${rootId}{height:var(--app-height,100dvh)}`;
    document.head.appendChild(style);
  }

  const apply = (): void => {
    const vv = window.visualViewport;
    document.documentElement.style.setProperty(
      "--app-height",
      `${vv ? vv.height : window.innerHeight}px`,
    );
  };

  let rafId = 0;
  let lateId = 0;
  const sync = (): void => {
    if (rafId) window.cancelAnimationFrame(rafId);
    rafId = window.requestAnimationFrame(() => {
      rafId = 0;
      apply();
    });
    if (lateId) window.clearTimeout(lateId);
    lateId = window.setTimeout(apply, 300);
  };

  const vv = window.visualViewport;
  vv?.addEventListener("resize", sync);
  vv?.addEventListener("scroll", sync);
  window.addEventListener("orientationchange", sync);
  apply();

  return () => {
    vv?.removeEventListener("resize", sync);
    vv?.removeEventListener("scroll", sync);
    window.removeEventListener("orientationchange", sync);
    if (rafId) window.cancelAnimationFrame(rafId);
    if (lateId) window.clearTimeout(lateId);
  };
}
